default_index:
  path: /
  defaults: { _controller: "AppBundle:Default:index" }
  methods:  GET

default_demo:
  path: /demo
  defaults: { _controller: "AppBundle:Default:demo"  }
  methods:  POST

default:login:
  path: /login
  defaults: { _controller: "AppBundle:Default:login" }
  methods: POST

default:profile:
  path: /profile
  defaults: { _controller: "AppBundle:Default:profile" }
  methods: GET
