BackendBundle\Entity\AnswerCentury:
    type: entity
    table: answer_century
    indexes:
        question_century_id:
            columns:
                - question_century_id
    id:
        id:
            type: integer
            nullable: false
            options:
                unsigned: false
            id: true
            generator:
                strategy: IDENTITY
    fields:
        name:
            type: text
            nullable: false
            length: 65535
            options:
                fixed: false
        status:
            type: integer
            nullable: false
            options:
                unsigned: false
                default: '1'
        createTime:
            type: datetime
            nullable: false
            column: create_time
        updateTime:
            type: datetime
            nullable: true
            column: update_time
    manyToOne:
        questionCentury:
            targetEntity: QuestionCentury
            cascade: {  }
            fetch: LAZY
            mappedBy: null
            inversedBy: null
            joinColumns:
                question_century_id:
                    referencedColumnName: id
            orphanRemoval: false
    lifecycleCallbacks: {  }
