BackendBundle\Entity\AnswerIneeTeacher:
    type: entity
    table: answer_inee_teacher
    indexes:
        answer_inee_teacher_ibfk_1:
            columns:
                - evaluation_inee_id
        answer_inee_teacher_ibfk_2:
            columns:
                - teacher_id
        answer_inee_teacher_ibfk_3:
            columns:
                - answer_inee_id
        answer_inee_teacher_ibfk_4:
            columns:
                - dimension_id
    id:
        id:
            type: integer
            nullable: false
            options:
                unsigned: false
            id: true
            generator:
                strategy: IDENTITY
    fields:
        total:
            type: integer
            nullable: false
            options:
                unsigned: false
        createTime:
            type: datetime
            nullable: false
            column: create_time
        updateTime:
            type: datetime
            nullable: true
            column: update_time
    manyToOne:
        evaluationInee:
            targetEntity: EvaluationInee
            cascade: {  }
            fetch: LAZY
            mappedBy: null
            inversedBy: null
            joinColumns:
                evaluation_inee_id:
                    referencedColumnName: id
            orphanRemoval: false
        teacher:
            targetEntity: Teacher
            cascade: {  }
            fetch: LAZY
            mappedBy: null
            inversedBy: null
            joinColumns:
                teacher_id:
                    referencedColumnName: id
            orphanRemoval: false
        answerInee:
            targetEntity: AnswerInee
            cascade: {  }
            fetch: LAZY
            mappedBy: null
            inversedBy: null
            joinColumns:
                answer_inee_id:
                    referencedColumnName: id
            orphanRemoval: false
        dimension:
            targetEntity: Dimension
            cascade: {  }
            fetch: LAZY
            mappedBy: null
            inversedBy: null
            joinColumns:
                dimension_id:
                    referencedColumnName: id
            orphanRemoval: false
    lifecycleCallbacks: {  }
