BackendBundle\Entity\EvaluationTeacher:
    type: entity
    table: evaluation_teacher
    indexes:
        teacher_id:
            columns:
                - teacher_id
        evaluation_id:
            columns:
                - evaluation_id
    id:
        id:
            type: integer
            nullable: false
            options:
                unsigned: false
            id: true
            generator:
                strategy: IDENTITY
    fields:
        score:
            type: string
            nullable: false
            length: 10
            options:
                fixed: false
        status:
            type: integer
            nullable: false
            options:
                unsigned: false
        createTime:
            type: datetime
            nullable: false
            options:
                default: '0000-00-00 00:00:00'
            column: create_time
        updateTime:
            type: datetime
            nullable: false
            options:
                default: '0000-00-00 00:00:00'
            column: update_time
    manyToOne:
        teacher:
            targetEntity: Teacher
            cascade: {  }
            fetch: LAZY
            mappedBy: null
            inversedBy: null
            joinColumns:
                teacher_id:
                    referencedColumnName: id
            orphanRemoval: false
        evaluation:
            targetEntity: Evaluation
            cascade: {  }
            fetch: LAZY
            mappedBy: null
            inversedBy: null
            joinColumns:
                evaluation_id:
                    referencedColumnName: id
            orphanRemoval: false
    lifecycleCallbacks: {  }
