BackendBundle\Entity\Indicator:
    type: entity
    table: indicator
    indexes:
        parameter_id:
            columns:
                - parameter_id
    id:
        id:
            type: integer
            nullable: false
            options:
                unsigned: false
            id: true
            generator:
                strategy: IDENTITY
    fields:
        name:
            type: text
            nullable: false
            length: 65535
            options:
                fixed: false
        createTime:
            type: datetime
            nullable: false
            column: create_time
        updateTime:
            type: datetime
            nullable: true
            column: update_time
    manyToOne:
        parameter:
            targetEntity: Parameter
            cascade: {  }
            fetch: LAZY
            mappedBy: null
            inversedBy: null
            joinColumns:
                parameter_id:
                    referencedColumnName: id
            orphanRemoval: false
    lifecycleCallbacks: {  }
