BackendBundle\Entity\Parameter:
    type: entity
    table: parameter
    indexes:
        dimension_id:
            columns:
                - dimension_id
    id:
        id:
            type: integer
            nullable: false
            options:
                unsigned: false
            id: true
            generator:
                strategy: IDENTITY
    fields:
        name:
            type: text
            nullable: false
            length: 65535
            options:
                fixed: false
        createTime:
            type: datetime
            nullable: false
            column: create_time
        updateTime:
            type: datetime
            nullable: true
            column: update_time
    manyToOne:
        dimension:
            targetEntity: Dimension
            cascade: {  }
            fetch: LAZY
            mappedBy: null
            inversedBy: null
            joinColumns:
                dimension_id:
                    referencedColumnName: id
            orphanRemoval: false
    lifecycleCallbacks: {  }
