BackendBundle\Entity\SkillCentury:
    type: entity
    table: skill_century
    id:
        id:
            type: integer
            nullable: false
            options:
                unsigned: false
            id: true
            generator:
                strategy: IDENTITY
    fields:
        name:
            type: string
            nullable: false
            length: 100
            options:
                fixed: false
        createTime:
            type: datetime
            nullable: false
            column: create_time
        updateTime:
            type: datetime
            nullable: true
            column: update_time
        status:
            type: boolean
            nullable: false
            options:
                    default: true
            column: status
        deleteTime:
            type: datetime
            nullable: false
            options:
                default: '0000-00-00 00:00:00'
            column: delete_time            
    lifecycleCallbacks: {  }
