<?php

namespace Proxies\__CG__\BackendBundle\Entity;

/**
 * DO NOT EDIT THIS FILE - IT WAS CREATED BY DOCTRINE'S PROXY GENERATOR
 */
class User extends \BackendBundle\Entity\User implements \Doctrine\ORM\Proxy\Proxy
{
    /**
     * @var \Closure the callback responsible for loading properties in the proxy object. This callback is called with
     *      three parameters, being respectively the proxy object to be initialized, the method that triggered the
     *      initialization process and an array of ordered parameters that were passed to that method.
     *
     * @see \Doctrine\Common\Persistence\Proxy::__setInitializer
     */
    public $__initializer__;

    /**
     * @var \Closure the callback responsible of loading properties that need to be copied in the cloned object
     *
     * @see \Doctrine\Common\Persistence\Proxy::__setCloner
     */
    public $__cloner__;

    /**
     * @var boolean flag indicating if this object was already initialized
     *
     * @see \Doctrine\Common\Persistence\Proxy::__isInitialized
     */
    public $__isInitialized__ = false;

    /**
     * @var array properties to be lazy loaded, with keys being the property
     *            names and values being their default values
     *
     * @see \Doctrine\Common\Persistence\Proxy::__getLazyProperties
     */
    public static $lazyPropertiesDefaults = [];



    /**
     * @param \Closure $initializer
     * @param \Closure $cloner
     */
    public function __construct($initializer = null, $cloner = null)
    {

        $this->__initializer__ = $initializer;
        $this->__cloner__      = $cloner;
    }







    /**
     * 
     * @return array
     */
    public function __sleep()
    {
        if ($this->__isInitialized__) {
            return ['__isInitialized__', '' . "\0" . 'BackendBundle\\Entity\\User' . "\0" . 'id', '' . "\0" . 'BackendBundle\\Entity\\User' . "\0" . 'email', '' . "\0" . 'BackendBundle\\Entity\\User' . "\0" . 'passwordHash', '' . "\0" . 'BackendBundle\\Entity\\User' . "\0" . 'passwordResetToken', '' . "\0" . 'BackendBundle\\Entity\\User' . "\0" . 'authKey', '' . "\0" . 'BackendBundle\\Entity\\User' . "\0" . 'status', '' . "\0" . 'BackendBundle\\Entity\\User' . "\0" . 'lastVisitTime', '' . "\0" . 'BackendBundle\\Entity\\User' . "\0" . 'createTime', '' . "\0" . 'BackendBundle\\Entity\\User' . "\0" . 'updateTime', '' . "\0" . 'BackendBundle\\Entity\\User' . "\0" . 'userRole'];
        }

        return ['__isInitialized__', '' . "\0" . 'BackendBundle\\Entity\\User' . "\0" . 'id', '' . "\0" . 'BackendBundle\\Entity\\User' . "\0" . 'email', '' . "\0" . 'BackendBundle\\Entity\\User' . "\0" . 'passwordHash', '' . "\0" . 'BackendBundle\\Entity\\User' . "\0" . 'passwordResetToken', '' . "\0" . 'BackendBundle\\Entity\\User' . "\0" . 'authKey', '' . "\0" . 'BackendBundle\\Entity\\User' . "\0" . 'status', '' . "\0" . 'BackendBundle\\Entity\\User' . "\0" . 'lastVisitTime', '' . "\0" . 'BackendBundle\\Entity\\User' . "\0" . 'createTime', '' . "\0" . 'BackendBundle\\Entity\\User' . "\0" . 'updateTime', '' . "\0" . 'BackendBundle\\Entity\\User' . "\0" . 'userRole'];
    }

    /**
     * 
     */
    public function __wakeup()
    {
        if ( ! $this->__isInitialized__) {
            $this->__initializer__ = function (User $proxy) {
                $proxy->__setInitializer(null);
                $proxy->__setCloner(null);

                $existingProperties = get_object_vars($proxy);

                foreach ($proxy->__getLazyProperties() as $property => $defaultValue) {
                    if ( ! array_key_exists($property, $existingProperties)) {
                        $proxy->$property = $defaultValue;
                    }
                }
            };

        }
    }

    /**
     * 
     */
    public function __clone()
    {
        $this->__cloner__ && $this->__cloner__->__invoke($this, '__clone', []);
    }

    /**
     * Forces initialization of the proxy
     */
    public function __load()
    {
        $this->__initializer__ && $this->__initializer__->__invoke($this, '__load', []);
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     */
    public function __isInitialized()
    {
        return $this->__isInitialized__;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     */
    public function __setInitialized($initialized)
    {
        $this->__isInitialized__ = $initialized;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     */
    public function __setInitializer(\Closure $initializer = null)
    {
        $this->__initializer__ = $initializer;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     */
    public function __getInitializer()
    {
        return $this->__initializer__;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     */
    public function __setCloner(\Closure $cloner = null)
    {
        $this->__cloner__ = $cloner;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific cloning logic
     */
    public function __getCloner()
    {
        return $this->__cloner__;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     * @static
     */
    public function __getLazyProperties()
    {
        return self::$lazyPropertiesDefaults;
    }

    
    /**
     * {@inheritDoc}
     */
    public function getId()
    {
        if ($this->__isInitialized__ === false) {
            return (int)  parent::getId();
        }


        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getId', []);

        return parent::getId();
    }

    /**
     * {@inheritDoc}
     */
    public function setEmail($email)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setEmail', [$email]);

        return parent::setEmail($email);
    }

    /**
     * {@inheritDoc}
     */
    public function getEmail()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getEmail', []);

        return parent::getEmail();
    }

    /**
     * {@inheritDoc}
     */
    public function setPasswordHash($passwordHash)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setPasswordHash', [$passwordHash]);

        return parent::setPasswordHash($passwordHash);
    }

    /**
     * {@inheritDoc}
     */
    public function getPasswordHash()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getPasswordHash', []);

        return parent::getPasswordHash();
    }

    /**
     * {@inheritDoc}
     */
    public function setPasswordResetToken($passwordResetToken)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setPasswordResetToken', [$passwordResetToken]);

        return parent::setPasswordResetToken($passwordResetToken);
    }

    /**
     * {@inheritDoc}
     */
    public function getPasswordResetToken()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getPasswordResetToken', []);

        return parent::getPasswordResetToken();
    }

    /**
     * {@inheritDoc}
     */
    public function setStatus($status)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setStatus', [$status]);

        return parent::setStatus($status);
    }

    /**
     * {@inheritDoc}
     */
    public function getStatus()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getStatus', []);

        return parent::getStatus();
    }

    /**
     * {@inheritDoc}
     */
    public function setLastVisitTime($lastVisitTime)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setLastVisitTime', [$lastVisitTime]);

        return parent::setLastVisitTime($lastVisitTime);
    }

    /**
     * {@inheritDoc}
     */
    public function getLastVisitTime()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getLastVisitTime', []);

        return parent::getLastVisitTime();
    }

    /**
     * {@inheritDoc}
     */
    public function setCreateTime($createTime)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setCreateTime', [$createTime]);

        return parent::setCreateTime($createTime);
    }

    /**
     * {@inheritDoc}
     */
    public function getCreateTime()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getCreateTime', []);

        return parent::getCreateTime();
    }

    /**
     * {@inheritDoc}
     */
    public function setUpdateTime($updateTime)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setUpdateTime', [$updateTime]);

        return parent::setUpdateTime($updateTime);
    }

    /**
     * {@inheritDoc}
     */
    public function getUpdateTime()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getUpdateTime', []);

        return parent::getUpdateTime();
    }

    /**
     * {@inheritDoc}
     */
    public function setUserRole(\BackendBundle\Entity\UserRole $userRole = NULL)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setUserRole', [$userRole]);

        return parent::setUserRole($userRole);
    }

    /**
     * {@inheritDoc}
     */
    public function getUserRole()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getUserRole', []);

        return parent::getUserRole();
    }

    /**
     * {@inheritDoc}
     */
    public function getAuthKey()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getAuthKey', []);

        return parent::getAuthKey();
    }

    /**
     * {@inheritDoc}
     */
    public function setAuthKey($authKey)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setAuthKey', [$authKey]);

        return parent::setAuthKey($authKey);
    }

}
