<?php

namespace Proxies\__CG__\BackendBundle\Entity;

/**
 * DO NOT EDIT THIS FILE - IT WAS CREATED BY DOCTRINE'S PROXY GENERATOR
 */
class Evaluation extends \BackendBundle\Entity\Evaluation implements \Doctrine\ORM\Proxy\Proxy
{
    /**
     * @var \Closure the callback responsible for loading properties in the proxy object. This callback is called with
     *      three parameters, being respectively the proxy object to be initialized, the method that triggered the
     *      initialization process and an array of ordered parameters that were passed to that method.
     *
     * @see \Doctrine\Common\Persistence\Proxy::__setInitializer
     */
    public $__initializer__;

    /**
     * @var \Closure the callback responsible of loading properties that need to be copied in the cloned object
     *
     * @see \Doctrine\Common\Persistence\Proxy::__setCloner
     */
    public $__cloner__;

    /**
     * @var boolean flag indicating if this object was already initialized
     *
     * @see \Doctrine\Common\Persistence\Proxy::__isInitialized
     */
    public $__isInitialized__ = false;

    /**
     * @var array properties to be lazy loaded, with keys being the property
     *            names and values being their default values
     *
     * @see \Doctrine\Common\Persistence\Proxy::__getLazyProperties
     */
    public static $lazyPropertiesDefaults = [];



    /**
     * @param \Closure $initializer
     * @param \Closure $cloner
     */
    public function __construct($initializer = null, $cloner = null)
    {

        $this->__initializer__ = $initializer;
        $this->__cloner__      = $cloner;
    }







    /**
     * 
     * @return array
     */
    public function __sleep()
    {
        if ($this->__isInitialized__) {
            return ['__isInitialized__', '' . "\0" . 'BackendBundle\\Entity\\Evaluation' . "\0" . 'id', '' . "\0" . 'BackendBundle\\Entity\\Evaluation' . "\0" . 'name', '' . "\0" . 'BackendBundle\\Entity\\Evaluation' . "\0" . 'description', '' . "\0" . 'BackendBundle\\Entity\\Evaluation' . "\0" . 'numberQuestions', '' . "\0" . 'BackendBundle\\Entity\\Evaluation' . "\0" . 'minimumRating', '' . "\0" . 'BackendBundle\\Entity\\Evaluation' . "\0" . 'timeResolve', '' . "\0" . 'BackendBundle\\Entity\\Evaluation' . "\0" . 'createTime', '' . "\0" . 'BackendBundle\\Entity\\Evaluation' . "\0" . 'updateTime', '' . "\0" . 'BackendBundle\\Entity\\Evaluation' . "\0" . 'teacherFunction', '' . "\0" . 'BackendBundle\\Entity\\Evaluation' . "\0" . 'speciality', '' . "\0" . 'BackendBundle\\Entity\\Evaluation' . "\0" . 'educationLevel'];
        }

        return ['__isInitialized__', '' . "\0" . 'BackendBundle\\Entity\\Evaluation' . "\0" . 'id', '' . "\0" . 'BackendBundle\\Entity\\Evaluation' . "\0" . 'name', '' . "\0" . 'BackendBundle\\Entity\\Evaluation' . "\0" . 'description', '' . "\0" . 'BackendBundle\\Entity\\Evaluation' . "\0" . 'numberQuestions', '' . "\0" . 'BackendBundle\\Entity\\Evaluation' . "\0" . 'minimumRating', '' . "\0" . 'BackendBundle\\Entity\\Evaluation' . "\0" . 'timeResolve', '' . "\0" . 'BackendBundle\\Entity\\Evaluation' . "\0" . 'createTime', '' . "\0" . 'BackendBundle\\Entity\\Evaluation' . "\0" . 'updateTime', '' . "\0" . 'BackendBundle\\Entity\\Evaluation' . "\0" . 'teacherFunction', '' . "\0" . 'BackendBundle\\Entity\\Evaluation' . "\0" . 'speciality', '' . "\0" . 'BackendBundle\\Entity\\Evaluation' . "\0" . 'educationLevel'];
    }

    /**
     * 
     */
    public function __wakeup()
    {
        if ( ! $this->__isInitialized__) {
            $this->__initializer__ = function (Evaluation $proxy) {
                $proxy->__setInitializer(null);
                $proxy->__setCloner(null);

                $existingProperties = get_object_vars($proxy);

                foreach ($proxy->__getLazyProperties() as $property => $defaultValue) {
                    if ( ! array_key_exists($property, $existingProperties)) {
                        $proxy->$property = $defaultValue;
                    }
                }
            };

        }
    }

    /**
     * 
     */
    public function __clone()
    {
        $this->__cloner__ && $this->__cloner__->__invoke($this, '__clone', []);
    }

    /**
     * Forces initialization of the proxy
     */
    public function __load()
    {
        $this->__initializer__ && $this->__initializer__->__invoke($this, '__load', []);
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     */
    public function __isInitialized()
    {
        return $this->__isInitialized__;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     */
    public function __setInitialized($initialized)
    {
        $this->__isInitialized__ = $initialized;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     */
    public function __setInitializer(\Closure $initializer = null)
    {
        $this->__initializer__ = $initializer;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     */
    public function __getInitializer()
    {
        return $this->__initializer__;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     */
    public function __setCloner(\Closure $cloner = null)
    {
        $this->__cloner__ = $cloner;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific cloning logic
     */
    public function __getCloner()
    {
        return $this->__cloner__;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     * @static
     */
    public function __getLazyProperties()
    {
        return self::$lazyPropertiesDefaults;
    }

    
    /**
     * {@inheritDoc}
     */
    public function getId()
    {
        if ($this->__isInitialized__ === false) {
            return (int)  parent::getId();
        }


        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getId', []);

        return parent::getId();
    }

    /**
     * {@inheritDoc}
     */
    public function setName($name)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setName', [$name]);

        return parent::setName($name);
    }

    /**
     * {@inheritDoc}
     */
    public function getName()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getName', []);

        return parent::getName();
    }

    /**
     * {@inheritDoc}
     */
    public function setDescription($description)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setDescription', [$description]);

        return parent::setDescription($description);
    }

    /**
     * {@inheritDoc}
     */
    public function getDescription()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getDescription', []);

        return parent::getDescription();
    }

    /**
     * {@inheritDoc}
     */
    public function setNumberQuestions($numberQuestions)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setNumberQuestions', [$numberQuestions]);

        return parent::setNumberQuestions($numberQuestions);
    }

    /**
     * {@inheritDoc}
     */
    public function getNumberQuestions()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getNumberQuestions', []);

        return parent::getNumberQuestions();
    }

    /**
     * {@inheritDoc}
     */
    public function setMinimumRating($minimumRating)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setMinimumRating', [$minimumRating]);

        return parent::setMinimumRating($minimumRating);
    }

    /**
     * {@inheritDoc}
     */
    public function getMinimumRating()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getMinimumRating', []);

        return parent::getMinimumRating();
    }

    /**
     * {@inheritDoc}
     */
    public function setTimeResolve($timeResolve)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setTimeResolve', [$timeResolve]);

        return parent::setTimeResolve($timeResolve);
    }

    /**
     * {@inheritDoc}
     */
    public function getTimeResolve()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getTimeResolve', []);

        return parent::getTimeResolve();
    }

    /**
     * {@inheritDoc}
     */
    public function setCreateTime($createTime)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setCreateTime', [$createTime]);

        return parent::setCreateTime($createTime);
    }

    /**
     * {@inheritDoc}
     */
    public function getCreateTime()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getCreateTime', []);

        return parent::getCreateTime();
    }

    /**
     * {@inheritDoc}
     */
    public function setUpdateTime($updateTime)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setUpdateTime', [$updateTime]);

        return parent::setUpdateTime($updateTime);
    }

    /**
     * {@inheritDoc}
     */
    public function getUpdateTime()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getUpdateTime', []);

        return parent::getUpdateTime();
    }

    /**
     * {@inheritDoc}
     */
    public function setTeacherFunction(\BackendBundle\Entity\TeacherFunction $teacherFunction = NULL)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setTeacherFunction', [$teacherFunction]);

        return parent::setTeacherFunction($teacherFunction);
    }

    /**
     * {@inheritDoc}
     */
    public function getTeacherFunction()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getTeacherFunction', []);

        return parent::getTeacherFunction();
    }

    /**
     * {@inheritDoc}
     */
    public function setSpeciality(\BackendBundle\Entity\Speciality $speciality = NULL)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setSpeciality', [$speciality]);

        return parent::setSpeciality($speciality);
    }

    /**
     * {@inheritDoc}
     */
    public function getSpeciality()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getSpeciality', []);

        return parent::getSpeciality();
    }

    /**
     * {@inheritDoc}
     */
    public function setEducationLevel(\BackendBundle\Entity\EducationLevel $educationLevel = NULL)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setEducationLevel', [$educationLevel]);

        return parent::setEducationLevel($educationLevel);
    }

    /**
     * {@inheritDoc}
     */
    public function getEducationLevel()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getEducationLevel', []);

        return parent::getEducationLevel();
    }

}
